[2025-07-15 15:58:21,654] INFO - DataFrame loaded successfully.
[2025-07-15 15:58:21,677] WARNING -  * Debugger is active!
[2025-07-15 15:58:21,680] INFO -  * Debugger PIN: 240-075-977
[2025-07-15 15:58:21,714] INFO - 127.0.0.1 - - [15/Jul/2025 15:58:21] "GET / HTTP/1.1" 200 -
[2025-07-15 15:58:39,867] WARNING - Timeout: No speech detected.
[2025-07-15 15:58:39,868] ERROR - Error in [C:\Users\DELL\Desktop\mental_health_bot\modules\voice_input.py] at line [37]: Voice input timeout
[2025-07-15 15:58:39,880] INFO - 127.0.0.1 - - [15/Jul/2025 15:58:39] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
[2025-07-15 15:58:40,220] INFO - 127.0.0.1 - - [15/Jul/2025 15:58:40] "[36mGET /process?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
[2025-07-15 15:58:40,221] INFO - 127.0.0.1 - - [15/Jul/2025 15:58:40] "[36mGET /process?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
[2025-07-15 15:58:40,482] INFO - 127.0.0.1 - - [15/Jul/2025 15:58:40] "GET /process?__debugger__=yes&cmd=resource&f=console.png&s=8UJ7jlyKDaacpUuBa7rr HTTP/1.1" 200 -
[2025-07-15 16:00:37,634] INFO - 127.0.0.1 - - [15/Jul/2025 16:00:37] "GET / HTTP/1.1" 200 -
[2025-07-15 16:00:47,695] INFO - Voice input saved: static/audio\user_input.wav
[2025-07-15 16:00:49,095] INFO - HTTP Request: POST https://api.groq.com/openai/v1/audio/transcriptions "HTTP/1.1 200 OK"
[2025-07-15 16:00:49,096] INFO - Transcription successful.
[2025-07-15 16:00:49,096] INFO - Running emotion and intent classification...
[2025-07-15 16:00:49,102] INFO - No specific intent matched. Defaulting to 'general_support'
[2025-07-15 16:00:49,529] INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
[2025-07-15 16:00:49,612] INFO - Emotion: الحزن | Intent: تفريغ مشاعر
[2025-07-15 16:00:49,613] INFO -  Building culturally adapted prompt...
[2025-07-15 16:00:59,569] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[2025-07-15 16:00:59,574] INFO - GPT-4o responded in 9.96s
[2025-07-15 16:00:59,583] WARNING - Term not found. Returning input term: أهلاً وسهلاً فيك، أقدر مشاعرك اللي تعبر عنها. أحياناً القلب يحس بأشياء كثيرة وما نقدر نحدد شو السبب. يمكن يكون في شي يشغلك أو مضايقك. 

تذكر إن التعبير عن مشاعرك خطوة مهمة، وكونك شاركتني هذا الشي يعني إنك واعي بأحاسيسك. حاول تاخذ لك وقت تهدأ فيه، يمكن تساعدك الصلاة أو قراءة القرآن في تهدئة النفس. وإذا تحس إنك تحتاج تتكلم أكثر، أنا هنا أسمع لك. 

وإذا كان الموضوع مستمر أو يسبب لك قلق كبير، ممكن يكون من الجيد إنك تتواصل مع مختص نفسي في منطقتك. سلامت قلبك، وإن شاء الله تلقى الراحة اللي تحتاجها.
[2025-07-15 16:01:00,273] INFO - HTTP Request: POST https://api.elevenlabs.io/v1/text-to-speech/DANw8bnAVbjDEHwZIoYa?output_format=mp3_22050_32 "HTTP/1.1 401 Unauthorized"
[2025-07-15 16:01:00,274] ERROR - [TTS ERROR] Failed to generate Arabic TTS
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\mental_health_bot\modules\tts_engine.py", line 59, in speak_arabic_emotional
    for chunk in audio_stream:
  File "C:\Users\DELL\anaconda3\envs\health_chatbot\lib\site-packages\elevenlabs\text_to_speech\client.py", line 163, in convert
    with self._raw_client.convert(
  File "C:\Users\DELL\anaconda3\envs\health_chatbot\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\DELL\anaconda3\envs\health_chatbot\lib\site-packages\elevenlabs\text_to_speech\raw_client.py", line 211, in convert
    yield _stream()
  File "C:\Users\DELL\anaconda3\envs\health_chatbot\lib\site-packages\elevenlabs\text_to_speech\raw_client.py", line 209, in _stream
    raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
elevenlabs.core.api_error.ApiError: headers: {'date': 'Tue, 15 Jul 2025 11:00:59 GMT', 'server': 'uvicorn', 'content-length': '173', 'content-type': 'application/json', 'access-control-allow-origin': '*', 'access-control-allow-headers': '*', 'access-control-allow-methods': 'POST, PATCH, OPTIONS, DELETE, GET, PUT', 'access-control-max-age': '600', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'x-trace-id': 'd25c3e213a75c6b4e54fb657ca45dadd', 'x-region': 'us-central1', 'via': '1.1 google, 1.1 google', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'}, status_code: 401, body: {'detail': {'status': 'quota_exceeded', 'message': 'This request exceeds your quota of 10000. You have 216 credits remaining, while 496 credits are required for this request.'}}
[2025-07-15 16:01:00,280] INFO -  * Detected change in 'C:\\Users\\DELL\\anaconda3\\envs\\health_chatbot\\Lib\\site-packages\\elevenlabs\\text_to_speech\\client.py', reloading
[2025-07-15 16:01:00,286] ERROR - Error in [C:\Users\DELL\Desktop\mental_health_bot\modules\tts_engine.py] at line [59]: headers: {'date': 'Tue, 15 Jul 2025 11:00:59 GMT', 'server': 'uvicorn', 'content-length': '173', 'content-type': 'application/json', 'access-control-allow-origin': '*', 'access-control-allow-headers': '*', 'access-control-allow-methods': 'POST, PATCH, OPTIONS, DELETE, GET, PUT', 'access-control-max-age': '600', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'x-trace-id': 'd25c3e213a75c6b4e54fb657ca45dadd', 'x-region': 'us-central1', 'via': '1.1 google, 1.1 google', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'}, status_code: 401, body: {'detail': {'status': 'quota_exceeded', 'message': 'This request exceeds your quota of 10000. You have 216 credits remaining, while 496 credits are required for this request.'}}
[2025-07-15 16:01:00,287] INFO -  * Detected change in 'C:\\Users\\DELL\\anaconda3\\envs\\health_chatbot\\Lib\\contextlib.py', reloading
[2025-07-15 16:01:00,287] INFO -  * Detected change in 'C:\\Users\\DELL\\anaconda3\\envs\\health_chatbot\\Lib\\site-packages\\elevenlabs\\text_to_speech\\raw_client.py', reloading
[2025-07-15 16:01:00,297] INFO - 127.0.0.1 - - [15/Jul/2025 16:01:00] "[35m[1mPOST /process HTTP/1.1[0m" 500 -
